// Flattens the stylesheet the package ships: fonts, tokens, then the site's
// globals.css (resets, keyframes, hover states, mock scaling, responsive
// utilities). One file, no @imports - consumers link exactly this.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const part = (p) => readFileSync(join(root, p), 'utf8').trim();
writeFileSync(
  join(root, 'styles.css'),
  [
    '/* @medkong/ds - fonts, tokens, and the site\'s global CSS. Generated by scripts/build-css.mjs; do not edit. */',
    part('fonts.css'),
    part('tokens.css'),
    part('../../app/globals.css'),
  ].join('\n\n') + '\n',
);
console.log('styles.css written');
